# Generated by Django 4.1.4 on 2022-12-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
